[package]
name = "make"
description = "A utility for just making files and directories."
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = "1.0.98"
atty = "0.2.14"
clap = { version = "4.5.39", features = ["derive"] }

[dev-dependencies]
tempfile = "3.20.0"
